### ISSUE TITLE
No audio stream.

### ISSUE THREAD

**Issue by micgus** [s1lvester/docker-snapcast-multiroomaudio#5]
Heya!
Thanks for sharing your config first off, much appreciated.
I'm currently running the same setup but the snapserver is hosted on one of my Pi's but i want it centralised in a container instead.

Now to my question.
I cannot get any sound on the snapclients i'm connecting.. I can see that theres not much config done to the snapserver out of the box, should it work after it has been deployed or do i need to configure snapserver, shairport and what not, as well?
(My snapcast & linux skills are terrible. )

**Comment by s1lvester** [comment]
Hi. Usually the problems with audio output seem to lie within the routing.
For me and some others this seems to work out of the box. Your milage may vary...

Putting everything into linux containers is indeed a bit advanced and I agree that this solution is not very pretty. Now - almost two years after putting this together I‘m pretty sure I wouldn‘t implement it the same way.

I think that it is more or less impossible to debug your problem from afar, but here‘s my tip:
start with a fresh virtual machine or ubuntu docker image and try to reimplement the steps taken in the „Dockerfile“. In my experience most problems seem to work out themselves during this process 😉
